language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
gemfile:
  - Gemfile.4.2.mysql2
  - Gemfile.4.2.pg
  - Gemfile.4.2.sqlite3
  - Gemfile.5.2.mysql2
  - Gemfile.5.2.pg
  - Gemfile.5.2.sqlite3
  - Gemfile.6.0.mysql2
  - Gemfile.6.0.pg
  - Gemfile.6.0.sqlite3
matrix:
  exclude:
    - rvm: 2.4.6
      gemfile: Gemfile.6.0.mysql2
    - rvm: 2.4.6
      gemfile: Gemfile.6.0.pg
    - rvm: 2.4.6
      gemfile: Gemfile.6.0.sqlite3
install:
  # Replace default Travis CI bundler script with a version that doesn't
  # explode when lockfile doesn't match recently bumped version
  - bundle install --no-deployment --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
before_install:
  - gem install bundler -v 1.15.4
  - export TZ=America/New_York
before_script:
  - psql -c 'create database actionset_test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS actionset_test;'
after_success:
  - bash < (curl -s https://codecov.io/bash)
