language: ruby
sudo: false
cache: bundler
rvm:
  - 2.7.0
  - 2.6.5
  - 2.5.7
  - 2.4.9
gemfile:
  - gemfiles/Gemfile[rails-4.2.x][mysql2-0.3.x]
  - gemfiles/Gemfile[rails-4.2.x][pg-0.11.x]
  - gemfiles/Gemfile[rails-4.2.x][sqlite3-1.3.x]
  - gemfiles/Gemfile[rails-5.2.x][mysql2-0.4.x]
  - gemfiles/Gemfile[rails-5.2.x][pg-0.18.x]
  - gemfiles/Gemfile[rails-5.2.x][sqlite3-1.4.x]
  - gemfiles/Gemfile[rails-6.0.x][mysql2-0.4.x]
  - gemfiles/Gemfile[rails-6.0.x][pg-0.18.x]
  - gemfiles/Gemfile[rails-6.0.x][sqlite3-1.4.x]
matrix:
  exclude:
    - rvm: 2.4.9
      gemfile: gemfiles/Gemfile[rails-6.0.x][mysql2-0.4.x]
    - rvm: 2.4.9
      gemfile: gemfiles/Gemfile[rails-6.0.x][pg-0.18.x]
    - rvm: 2.4.9
      gemfile: gemfiles/Gemfile[rails-6.0.x][sqlite3-1.4.x]
install:
  # Replace default Travis CI bundler script with a version that doesn't
  # explode when lockfile doesn't match recently bumped version
  - bundle install --no-deployment --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
before_install:
  - gem install bundler -v 1.15.4
  - bundle exec rake matrix:install
  - export TZ=America/New_York
before_script:
  - psql -c 'create database actionset_test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS actionset_test;'
services:
  - mysql
  - postgresql
after_success:
  - bash < (curl -s https://codecov.io/bash)
